// A 7x14 bitmap font for printable ASCII (32-126), for labelling the images
// render_audio draws without a canvas library. Rasterized once from DejaVu
// Sans Mono at 12 px (see scripts/gen-font.py): one bit per pixel, rows top
// to bottom, glyphs in code-point order.

export const GLYPH_WIDTH = 7;
export const GLYPH_HEIGHT = 14;
const FIRST = 32;
const LAST = 126;

const BITS = Buffer.from(
  "AAAAAAAAAAAAAAAAAAAQIECBAgAIEAAAAAAKFCgAAAAAAAAAAAAAAoU/LFP6RQAAAAAAQcdKDA4WqPCBAAAAYSJDIYmEiQwAAAAADjBgQcbYqJ+AAAAAAQIEAAAAAAAAAAAAEGCBAgwIECBgQAAAEBAgYMCDBggQQAAAAAQqOHFQgAAAAAAAAAAABAgR/ECBAAAAAAAAAAAAAAAgQYAAAAAAAAAABwAAAAAAAAAAAAAAAAACBAAAAAAAQYIEECCBBAgAAAAA42RIlaJE2OAAAAAAeDBgwYMGDDwAAAAADiYECCDDDB8AAAAAA4mBBjgIEieAAAAAADDhxZMmfhgwAAAAAHyBA8DAgSZ4AAAAAA4yQPGSJEyOAAAAAAfAgwQIMEGCAAAAAADjJEyOIkSI8AAAAAA4mRIkx4EmOAAAAAAAAAAgQAACBAAAAAAAAAAIEAAAgQYAAAAAAABjmDAcDAAAAAAAAAAAD+A/gAAAAAAAAADA4Dh3GAAAAAAAA4iBBBAgAIEAAAAAAAHmaGfZsz0DA8AAABhwoUbMnyPCAAAAAB4iRInyJGjfAAAAAAPEECBAgQEDwAAAAAHiZEiRokSZ4AAAAAB8gQIHyBAgfgAAAAAfsGDB8wYMGAAAAAADzJAgTo0bM8AAAAABEiRInyJEiRAAAAAAfCBAgQIECHwAAAAADwYMGDBgwR4AAAAABGmWOHCxMiRgAAAAAYMGDBgwYMH4AAAAAMfPv126cOHCAAAAABkyZKlS5MmRAAAAAAOMkSNGjRMjgAAAAAHyNGjfIECBAAAAAAA4yRI0aNEyOBgQAAAeJkSJ4mRI0IAAAAADjJAwOAgSI4AAAAAD+IECBAgQIEAAAAAARIkSJEiRMjgAAAAAMaNEyLFChwYAAAAACDB07X7Zs2ZAAAAAARsigwYcLIsYAAAAAMaIscGCBAgQAAAAAB+CDBBBggwfgAAAAMECBAgQIECBAwAAAAECAgQECAgQMCAAABwYMGDBgwYMGHAAAAAGFkQAAAAAAAAAAAAAAAAAAAAAAAAAfwBAQAAAAAAAAAAAAAAAAAHgIEeRJnwAAAAIECB4yRI0TJ4AAAAAAAAHEGCBgQHAAAAACBAjzZEiRNjwAAAAAAAA4yRP0DI8AAAAAYQIfCBAgQIEAAAAAAAADzZEiRNjwIMcAIECB4yRIkSJEAAAAAgAAcCBAgQIfAAAAAMAADgwYMGDBgwQ4AMGDBk0cPGjJmAAAADgQIECBAgQIHAAAAAAAAHytSpUqVIAAAAAAAB4yRIkSJEAAAAAAAAOMkSJEyOAAAAAAAAHjJEjRMniBAgAAAAA82RIkTY8CBAgAAAAPmCBAgQIAAAAAAAADjJgcBIjgAAAAADBh8YMGDAgcAAAAAAAARIkSJE2PAAAAAAAAEaJkWKHBgAAAAAAACDB0r2zZsAAAAAAAARFjgg42RAAAAAAAAEaJkWKHBggwwAAAAB8GCCDDB8AAAAAYQIECHAgQIEBgAAAIECBAgQIECBAgQAAOBAgQIDDBAgQ4AAAAAAAAAHI4AAAAAAA",
  "base64",
);

/** Whether pixel (x, y) of `ch`'s glyph is set. Unknown characters draw as "?". */
export function glyphPixel(ch: string, x: number, y: number): boolean {
  let code = ch.charCodeAt(0);
  if (code < FIRST || code > LAST) code = "?".charCodeAt(0);
  const bit = ((code - FIRST) * GLYPH_HEIGHT + y) * GLYPH_WIDTH + x;
  return ((BITS[bit >> 3]! >> (7 - (bit & 7))) & 1) === 1;
}
